#!/usr/bin/env bash
# Uninstall the rice deployed by install.sh.
#
# Removes what the installer deployed (copied config dirs, generated files,
# ~/.zshrc symlink, color-bridge symlinks) and restores the most recent
# timestamped backup if one exists. Never deletes unrelated user data:
# directories that contain files the installer did not deploy are left alone
# and reported.
#
# Usage: ./uninstall.sh [--yes]
#   USERNAME=someuser ./uninstall.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ASSUME_YES=0
[[ "${1:-}" == "--yes" ]] && ASSUME_YES=1

USERNAME="${USERNAME:-${SUDO_USER:-${USER:-}}}"
if [[ -z "${USERNAME:-}" || "$USERNAME" == "root" ]]; then
  USERNAME="$(awk -F: '$3>=1000 && $3<60000 {print $1; exit}' /etc/passwd 2>/dev/null || true)"
fi
[[ -n "${USERNAME:-}" && "$USERNAME" != "root" ]] || { echo "[-] cannot detect user" >&2; exit 1; }
HOME_DIR="$(getent passwd "$USERNAME" | cut -d: -f6)"
[[ -n "$HOME_DIR" && -d "$HOME_DIR" ]] || { echo "[-] no home for $USERNAME" >&2; exit 1; }
CONFIG_DIR="$HOME_DIR/.config"

run_as_user() {
  if [[ $EUID -eq 0 ]]; then su -s /bin/bash "$USERNAME" -c "export HOME='$HOME_DIR'; $*";
  elif [[ "$(id -un)" == "$USERNAME" ]]; then bash -c "export HOME='$HOME_DIR'; $*";
  else sudo -u "$USERNAME" env HOME="$HOME_DIR" bash -c "$*"; fi
}

if [[ $ASSUME_YES -eq 0 ]]; then
  read -r -p "Remove rice configs for $USERNAME? Backups will be restored when found. [y/N] " ans
  [[ "$ans" == [Yy]* ]] || { echo "Aborted."; exit 0; }
fi

MANAGED_DIRS="hypr quickshell wal rofi foot xdg-desktop-portal uwsm matugen"
BACKUP_ROOT="$HOME_DIR/.local/share/dotfiles-backups"
LATEST="$(ls -1d "$BACKUP_ROOT"/*/ 2>/dev/null | sort | tail -n 1 || true)"
# Older installer generations used a different backup location; honor those too.
[[ -n "$LATEST" ]] || LATEST="$(ls -1d "$HOME_DIR/.local/share/rice-backups"/*/ 2>/dev/null | sort | tail -n 1 || true)"

for d in $MANAGED_DIRS; do
  target="$CONFIG_DIR/$d"
  [[ -e "$target" || -L "$target" ]] || continue
  if [[ -n "$LATEST" && -e "$LATEST/${d}" ]]; then
    echo "[+] Restoring backup for $d"
    run_as_user "rm -rf '$target' && cp -a '$LATEST/${d}' '$target'"
  else
    # Only remove files that came from the repo; keep anything else.
    removed=0; kept=0
    while IFS= read -r -d '' f; do
      rel="${f#$target/}"
      if [[ -f "$REPO_DIR/$d/$rel" ]]; then rm -f "$f"; removed=$((removed+1)); else kept=$((kept+1)); fi
    done < <(find "$target" -type f -print0 2>/dev/null)
    find "$target" -type d -empty -delete 2>/dev/null || true
    echo "[+] $d: removed $removed deployed file(s), kept $kept unrelated file(s)"
    [[ -e "$target" ]] || echo "    $target fully removed"
  fi
done

# Generated files (portable monitor default + lyricsmpris link)
if [[ -f "$CONFIG_DIR/hypr/source-configs/monitors.lua" ]] \
   && grep -q 'Generated by install.sh' "$CONFIG_DIR/hypr/source-configs/monitors.lua" 2>/dev/null; then
  run_as_user "rm -f '$CONFIG_DIR/hypr/source-configs/monitors.lua'"
  echo "[+] removed installer-generated monitors.lua"
  if [[ -n "$LATEST" && -e "$LATEST/hypr/source-configs/monitors.lua" ]]; then
    run_as_user "cp -a '$LATEST/hypr/source-configs/monitors.lua' '$CONFIG_DIR/hypr/source-configs/monitors.lua'"
    echo "[+] restored monitors.lua from backup"
  fi
fi
if [[ -L "$HOME_DIR/.local/bin/lyricsmpris" ]]; then
  run_as_user "rm -f '$HOME_DIR/.local/bin/lyricsmpris'"
  echo "[+] removed ~/.local/bin/lyricsmpris symlink"
fi

echo
echo "Uninstall complete. Notes:"
echo "  - Packages were NOT removed (reinstall them manually if desired)."
echo "  - System services and login-manager settings were left alone."
