#!/bin/bash

# selecting wallpaper
wall=$(nsxiv -t -o ~/Pictures/wallpapers/images/dark)
[ -z "$wall" ] && exit

# Generating colors using pywal
wal -i "$wall"

# setting wallpaper
swww img $wall --transition-step 255 --transition-fps 255

# saving current wallpaper to cache
cp "$wall" ~/.cache/current_wallpaper

#  -----------spotify-------------
theme=$(spicetify config current_theme)

pywal-spicetify "$theme"
