#!/bin/bash

# selecting wallpaper
wall=$(nsxiv -t -o ~/Pictures/wallpapers/images/dark)
[ -z "$wall" ] && exit

# Generating colors using pywal
wal -i "$wall" -o ~/.local/src/pywalium/generate.sh

# Color for gtk using matugen
matugen image $wall --source-color-index 0

# setting wallpaper
swww img $wall --transition-type fade --transition-step 90 --transition-fps 60


# saving current wallpaper to cache
cp "$wall" ~/.cache/current_wallpaper

#  -----------spotify-------------
theme=$(spicetify config current_theme)

pywal-spicetify "$theme"
