-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("smooth", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1 } } })

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "popin 90%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "popin 90%",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "smooth",
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slide",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slide",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5,
    bezier = "smooth",
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 6,
    bezier = "smooth",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4,
    bezier = "smooth",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 6,
    bezier = "smooth",
    style = "slidevert",
})
