-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.cache/wal/colors-hyprland.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("colors-hyprland")

--###############
--## MONITORS ###
--###############

-- Source: ~/.config/hypr/source-configs/monitors.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.monitors")

--##################
--## MY PROGRAMS ###
--##################

-- Source: ~/.config/hypr/source-configs/programs.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.programs")

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- Source: ~/.config/hypr/source-configs/enviornment-variables.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.enviornment-variables")

--################
--## AUTOSTART ###
--################

-- Source: ~/.config/hypr/source-configs/autostarts.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.autostarts")

--##################
--## Appearance   ###
--##################

-- Source: ~/.config/hypr/source-configs/appearance.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.appearance")

--##################
--## Appearance   ###
--##################

-- source = ~/.config/hypr/source-configs/animation/minimal.lua
-- source = ~/.config/hypr/source-configs/animation/minimal-smoother.lua
-- Source: ~/.config/hypr/source-configs/animation/apple.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.animation.apple")
-- source = ~/.config/hypr/source-configs/animation/premium.lua

-- animations{
-- enabled = false
-- }

--############
--## INPUT ###
--############

-- Source: ~/.config/hypr/source-configs/input.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.input")

--##################
--## KEYBINDINGS ###
--##################

-- Source: ~/.config/hypr/source-configs/keybinds.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.keybinds")

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- Source: ~/.config/hypr/source-configs/window-rules.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.window-rules")

--##################
--## Layer rules ###
--##################

-- Source: ~/.config/hypr/source-configs/layer-rules.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("source-configs.layer-rules")

hl.config({
    debug = {
        damage_tracking = 0,
    },
})
