source = ~/.cache/wal/colors-hyprland.conf

################
### MONITORS ###
################

source = ~/.config/hypr/source-configs/monitors.conf


###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/source-configs/programs.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/source-configs/enviornment-variables.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/source-configs/autostarts.conf

###################
### Appearance  ###
###################

source = ~/.config/hypr/source-configs/appearance.conf

###################
### Appearance  ###
###################

# source = ~/.config/hypr/source-configs/animation/minimal.conf
# source = ~/.config/hypr/source-configs/animation/minimal-smoother.conf
source = ~/.config/hypr/source-configs/animation/apple.conf
# source = ~/.config/hypr/source-configs/animation/premium.conf

# animations{
# enabled = false
# }

#############
### INPUT ###
#############

source = ~/.config/hypr/source-configs/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/source-configs/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/source-configs/window-rules.conf

###################
### Layer rules ###
###################

source = ~/.config/hypr/source-configs/layer-rules.conf


debug {
    damage_tracking = 0
}
