source = ~/.cache/wal/colors-hyprland.conf

################
### MONITORS ###
################

source = ~/.config/hypr/source-configs/monitors.conf


###################
### MY PROGRAMS ###
###################

source = ~/.config/hypr/source-configs/programs.conf

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/source-configs/autostarts.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/source-configs/enviornment-variables.conf

###################
### Appearance  ###
###################

source = ~/.config/hypr/source-configs/appearance.conf


#############
### INPUT ###
#############

source = ~/.config/hypr/source-configs/input.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/source-configs/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/source-configs/window-rules.conf

###################
### Layer rules ###
###################

source = ~/.config/hypr/source-configs/layer-rules.conf
