-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768p@60",
    position = "0x0",
    scale = "1.00",
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    cursor = {
        no_hardware_cursors = false,
        no_warps = false,
    },
})

