-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 0,
        col = {
            active_border = color5 .. " " .. color12 .. " 45deg",
            inactive_border = color0,
        },
        resize_on_border = false,
        allow_tearing = true,
        layout = "dwindle",
    },
    decoration = {
        rounding = 10,
        rounding_power = 5,
        active_opacity = 1.0,
        inactive_opacity = 0.5,
        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            new_optimizations = true,
        },
    },
    dwindle = {
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
})

