exec-once =/home/xubm/.config/hypr/scripts/pywal-startup-script
exec-once = awww-daemon
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = waybar&
exec-once = /home/xubm/.local/bin/webcam-fix.sh
