exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP

exec-once = /home/xubm/.config/hypr/scripts/pywal-startup-script
exec-once = awww-daemon --no-cache
exec-once = /home/xubm/.config/hypr/scripts/startup.sh
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = waybar &
exec-once = /home/xubm/.local/bin/webcam-fix.sh
exec-once = ~/.scripts/wayclick/wayclick.sh

