-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("QT_STYLE_OVERRIDE", "Kvantum")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("AWWW_TRANSITION", "center")
hl.env("AWWW_TRANSITION_FPS", "60")
hl.env("AWWW_TRANSITION_DURATION", "2")
