env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_STYLE_OVERRIDE,Kvantum
env = QT_QPA_PLATFORM,wayland;xcb
# Force Wayland for Mozilla/Brave
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland


