input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    accel_profile = flat
    force_no_accel = false

    natural_scroll = false

    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5   # your mouse tuning stays here
}

# 3 finger gestures
gesture = 3, up, dispatcher, exec, playerctl play-pause
gesture = 3, left, dispatcher, exec, playerctl previous
gesture = 3, right, dispatcher, exec, playerctl next
# 4 finger gestures
gesture = 4, up, dispatcher, exec, playerctl volume 0.10+
gesture = 4, down, dispatcher, exec, playerctl volume 0.10-
