-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
        force_no_accel = false,
        natural_scroll = false,
        touchpad = {
            natural_scroll = false,
        },
    },
    gestures = {
        -- TUI: Slider [100 - 1000] - "Swipe Distance"
        workspace_swipe_distance = 300,
        -- TUI: Slider [0.0 - 1.0] - "Swipe Cancellation Threshold"
        workspace_swipe_cancel_ratio = 0.5,
        -- TUI: Toggle [true/false] - "Invert Swipe Direction"
        workspace_swipe_invert = true,
        -- TUI: Toggle [true/false] - "Swipe to Create New Workspace"
        workspace_swipe_create_new = true,
        -- TUI: Toggle [true/false] - "Swipe Forever" (Don't clamp at neighbors)
        workspace_swipe_forever = false,
    },
})

