layerrule {
  name = waybar-blur
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}
layerrule {
    name = rofi-blur
    blur = on
    ignore_alpha = 0.4
    match:namespace = rofi
}

layerrule {
  name = rofi-blur
  blur = on
  match:namespace = rofi
}

layerrule{
	name = sway-blur
	blur = on
	ignore_alpha = 0.5
	match:namespace = swaync-control-center
}
