-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    -- Ignore maximize requests from all apps. You'll probably like this.
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- Fix some dragging issues with XWayland
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

--#### SPOTIFY #####

hl.window_rule({
    name = "spotify-blur",
    match = {
        class = "Spotify",
    },
    opacity = 0.7,
})

--### cool-retro-term ####

hl.window_rule({
    name = "retro-term-blur",
    match = {
        class = "cool-retro-term",
    },
    opacity = 0.7,
})

--### foot ####

hl.window_rule({
    name = "foot",
    match = {
        title = "foot",
    },
    opacity = 0.7,
})

--### FIREFOX ####

hl.window_rule({
    name = "firefox-blur",
    match = {
        class = "firefox",
    },
    opacity = 0.85,
})

-- #### Brave ####
--
-- windowrule {
--     name = brave-blur
--
--     match:class = brave-browser
--     opacity = 0.8
-- }

--### Brave ####

hl.window_rule({
    name = "qutebrowser-blur",
    match = {
        class = "org.qutebrowser.qutebrowser",
    },
    opacity = 0.8,
})

hl.window_rule({
    name = "brave-youtube-noblur",
    match = {
        class = "brave-browser",
        title = ".*YouTube.*",
    },
    opacity = 1.0,
})

hl.window_rule({
    name = "brave-onlyflix-noblur",
    match = {
        class = "brave-browser",
        title = ".*OnlyFlix.*",
    },
    opacity = 1.0,
})

--### Thunar ####

hl.window_rule({
    name = "thunar-blur",
    match = {
        class = "thunar",
    },
    opacity = 0.75,
})

--### Obsidian ####
hl.window_rule({
    name = "obsidian-blur",
    match = {
        class = "obsidian",
    },
    opacity = 0.85,
})

--### zathura ####
hl.window_rule({
    name = "zathura-blur",
    match = {
        class = "org.pwmt.zathura",
    },
    opacity = 0.6,
})

--### zed ####
hl.window_rule({
    name = "zed-blur",
    match = {
        class = "dev.zed.Zed",
    },
    opacity = 0.85,
})

--### Librewolf ####

hl.window_rule({
    name = "Librewolf-blur",
    match = {
        class = "librewolf",
    },
    opacity = 0.7,
})

--### vesktop ####

hl.window_rule({
    name = "vesktop-blur",
    match = {
        class = "vesktop",
    },
    opacity = 0.8,
})

-- #### Mewsic ####
--
-- windowrule {
--     name = mewsic-blur
--     match:class = ^(mewsic)$
--     opacity = 0.80 0.80
-- }
