windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

##### SPOTIFY #####

windowrule {
    name = spotify-blur

    match:class = spotify
    opacity = 0.7
}

#### KITTY ####

windowrule {
    name = kitty-blur

    match:class = kitty
    opacity = 0.7
}

#### FIREFOX ####

windowrule {
    name = firefox-blur

    match:class = firefox
    opacity = 0.85
}

#### Brave ####

windowrule {
    name = brave-blur

    match:class = brave-browser
    opacity = 0.85
}

windowrule {
    name = thunar-blur

    match:class = thunar
    opacity = 0.75
}
