[general]
# Thick bars (you can bump this back to 50 if 12 is too chunky)
bars = 80

# CRITICAL: Do not let Cava guess the bar count
autobars = 0

# Smooth 60fps animations
framerate = 60

# Dynamic sensitivity settings
autosens = 1
sensitivity = 100

# Go to sleep after 5 seconds of silence to save resources
sleep_timer = 5


[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
# Map heights perfectly to the 150px Eww window
ascii_max_range = 150


[smoothing]
integral = 77
monstercat = 1
gravity = 100
ignore = 0
