# ~/.config/foot/foot.ini

# ===== PYWAL COLORS =====
# Include must be at the absolute top/main section
include=~/.cache/wal/colors-foot.ini

# ===== MAIN APPEARANCE & FONT =====

# font=Bm437 IBM VGA 8x16-2x:size=22,icomoon:size=16

font=icomoon:size=18, Terminess Nerd Font:size=18
line-height=30px

pad=10x10

# ===== SCROLLBACK =====
[scrollback]
lines=10000

# ===== CURSOR =====
[cursor]
style=underline
blink=yes

# ===== PERFORMANCE & BELL =====
[bell]
urgent=no
notify=no

# ===== OPACITY =====
[colors-dark]
alpha=0.8
blur=yes

# ===== TWEAKS =====
[tweak]
font-monospace-warn=no
